# Generated by Django 4.2.19 on 2025-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(default='', max_length=100, null=True, verbose_name='District')),
                ('year', models.PositiveIntegerField(default=0, null=True, verbose_name='Year')),
                ('yield_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yield Value')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Market Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Historical Data',
                'verbose_name_plural': 'Historical Data',
                'ordering': ['district', 'year'],
            },
        ),
    ]
