# Generated by Django 4.2.19 on 2025-02-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='crop_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Crop Name'),
        ),
    ]
